--  batch_run_id find
SELECT * FROM PROCUREMENT_DATALAKE_PP_DB.UTIL.S2C_BTCH_RUN_STAT_CNFGR 
WHERE BTCH_STAT <> 'Completed' ;AND BTCH_CD ='EPDP_BCH_001'; 

-- job stats with crnt batch run id
SELECT B.JOB_NM, B.TRGT_TBL,b.SRC_TBL  ,A.* FROM PROCUREMENT_DATALAKE_PP_DB.UTIL.S2C_JOB_RUN_STAT_CNFGR A,
PROCUREMENT_DATALAKE_PP_DB.UTIL.S2C_JOB_METADATA_CNFGR B
WHERE A.JOB_CD = B.JOB_CD AND A.BTCH_RUN_ID = 230 --AND B.JOB_NM ='J_INVC_HDR_SAT_CBS_DWH' 
AND  A.JOB_STAT <> 'Completed' --AND B.JOB_NM LIKE '%USER_BUYER%'
ORDER BY JOB_NM ; 
-- validation throws errow/ manual cls of validation
call PROCUREMENT_DATALAKE_DEV_DB.UTIL.S2C_VALDN_PROC('PROCUREMENT_DATALAKE_DEV_DB.UTIL.','EPDP_DWH_035',0,0); 
 

